name: syncfusion_localizations
description: Syncfusion Localizations package contains localized text for 77 cultures for all the applicable Syncfusion Flutter Widgets. 
version: 18.3.35+2
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_localizations

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

  syncfusion_flutter_core:
    git:
      url: https://github.com/annguyen-it/flutter-widgets.git
      path: ./packages/syncfusion_flutter_core

flutter: